drive_rabbit_node:
  ros__parameters:
    speed_motor: 100.0
    path_auto: "test6"

joystick_node:
  ros__parameters:
    type_joy: "xbox"

command_rabbit_node:
  ros__parameters:
    team: "blue"
    boot:
      pwm: 240.0
      delay: 0.1
      delayPre: 0.6
    dec:
      pwm: 80.0
      delay: 0.5
